---
platform: linux

inputs:
  - name: bosh-deployment
  - name: concourse-infra-for-fiwg
  - name: terraform

params:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  CLOUD_CONFIG_PATH:
  JUMPBOX_PRIVATE_KEY:
  JUMPBOX_URL:

run:
  path: concourse-infra-for-fiwg/ci/tasks/deploy-bosh-director/update-director-configs.sh
