---
platform: linux

inputs:
  - name: concourse-infra-for-fiwg
  - name: director-creds
  - name: jumpbox-creds
  - name: terraform

run:
  path: concourse-infra-for-fiwg/ci/tasks/update-credhub-credentials/update-credhub-credentials.sh
