---
platform: linux

inputs:
  - name: concourse-infra-for-fiwg

params:
  CREDHUB_CA_CERT:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  JUMPBOX_URL:
  JUMPBOX_PRIVATE_KEY:
  CAS_TO_ROTATE:

run:
  path: concourse-infra-for-fiwg/ci/tasks/cert-rotation/rotate-ca-certificate.rb
