#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ def add_concourse_namespace():
#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: concourse
#@ end

---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse
  labels:
    quarks.cloudfoundry.org/monitored: concourse

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "concourse-web"}})
---
spec:
  template:
    spec:
      initContainers:
      #@overlay/match by=overlay.subset({"name": "concourse-migration"})
      #@overlay/merge
      - name: concourse-migration
        env:
        #@overlay/match by=overlay.subset({"name": "CONCOURSE_POSTGRES_HOST"})
        #@overlay/replace
        - name: CONCOURSE_POSTGRES_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
      containers:
      #@overlay/match by=overlay.subset({"name": "concourse-web"})
      #@overlay/merge
      - name: concourse-web
        env:
        #@overlay/match by=overlay.subset({"name": "CONCOURSE_POSTGRES_HOST"})
        #@overlay/replace
        - name: CONCOURSE_POSTGRES_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP      #@overlay/append


--- #@ template.replace(overlay.apply(library.get("concourse").eval(), add_concourse_namespace()))
